ALTER TABLE trends ADD COLUMN rare_score INTEGER DEFAULT 0;
ALTER TABLE trends ADD COLUMN auth_score INTEGER DEFAULT 0;
ALTER TABLE trends ADD COLUMN dis_score INTEGER DEFAULT 0;
ALTER TABLE trends ADD COLUMN social_score INTEGER DEFAULT 0;
ALTER TABLE trends ADD COLUMN editorial_insight TEXT;
